travis:
  secure:
    BINSTAR_TOKEN: tjs6GZ/KEiQ7k/sMcM5DGIj+Szf6HTrpTpp6IqVlc9IMVoQewiQoeqvOaXhXS7y/IfdAzIMWVYBfNKBZ2SmqE6LGk5X7+dDtduMnWjcE1qPSt/Q9mF4SJoQg7j0zlIoqYwsMX16dYYW4yCfgGX+C/VZRCGPPaRRc0+jZSoKohhDzO0IWQenFjgQ9724D+Mx5wEkLsji6bcVUQm685oe4e6XEMB+IQ031kMYYWRQaK8eJeG0JIGg4aATYzxsSoTBrVMNpF3sy3+ZlME5bUbspT9prUMJ2deCTw5JMSgWrT3YK5gefDtF4DI/PyRJo8aQg8qa3P3oSQpQKLlVof2vvcHbDfCRlW/zQPz9csCPCsvL/rH+NzorphUkIlyBpwG9IlRpG8zm1NctT/fuqRQP9K0YmQKxFPxuQbuADO6MqMJdYZupCq74o2vY2j7WTf+HGP6X2cZ+tFQF2GAf3sF9J1qhcrjN2SELwwTfZeVungV6n/v8o2mfzNIJagHwUnEWUcji6pIiAYPuiDvTsGMCIJ8UIbalTfe97rK/C7u5uJY9Q6K7Jq+ryexogNNTsEnmirJyrwDw4FWW2bJTLc30iKpk6aqBlvhYaiclrZRlrQlcliD4m1TuSfU2eOSorGLPhw3yn8geTuN+ojPL3rur3bty8xa6QIISF05cXQl5JlY0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
